# Generated by Django 4.2.2 on 2023-06-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('its', '0002_alter_issue_project_id_contributor_and_more'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
